export const DUMMY_TASKS = [
  {
    id: "t1",
    userId: "u1",
    title: "Master Angular",
    summary:
      "Learn all the basic and advanced features of Angular & how to apply them.",
    dueDate: "2025-12-31",
  },
  {
    id: "t8",
    userId: "u1",
    title: "Write Angular tests",
    summary: "Create unit and integration tests for Angular components.",
    dueDate: "2024-11-30",
  },
  {
    id: "t9",
    userId: "u1",
    title: "Review TypeScript basics",
    summary: "Revise TypeScript fundamentals for better Angular development.",
    dueDate: "2024-12-15",
  },
  {
    id: "t4",
    userId: "u2",
    title: "Design landing page",
    summary: "Create an engaging design for the product landing page.",
    dueDate: "2024-07-20",
  },
  {
    id: "t10",
    userId: "u2",
    title: "Update branding guidelines",
    summary: "Revise and distribute updated branding guidelines to the team.",
    dueDate: "2024-08-05",
  },
  {
    id: "t11",
    userId: "u2",
    title: "Prepare pitch deck",
    summary: "Create a compelling pitch deck for the next client meeting.",
    dueDate: "2024-09-01",
  },
  {
    id: "t2",
    userId: "u3",
    title: "Build first prototype",
    summary: "Build a first prototype of the online shop website.",
    dueDate: "2024-05-31",
  },
  {
    id: "t3",
    userId: "u3",
    title: "Prepare issue template",
    summary:
      "Prepare and describe an issue template which will help with project management.",
    dueDate: "2024-06-15",
  },
  {
    id: "t12",
    userId: "u3",
    title: "Set up testing pipeline",
    summary: "Establish an automated pipeline for end-to-end testing.",
    dueDate: "2024-07-10",
  },
  {
    id: "t5",
    userId: "u4",
    title: "Organize team workshop",
    summary: "Plan and organize a workshop to align team goals for Q3.",
    dueDate: "2024-08-10",
  },
  {
    id: "t13",
    userId: "u4",
    title: "Audit team performance",
    summary:
      "Analyze and prepare a report on team performance for the quarter.",
    dueDate: "2024-09-15",
  },
  {
    id: "t14",
    userId: "u4",
    title: "Set OKRs for Q4",
    summary: "Define clear objectives and key results for the next quarter.",
    dueDate: "2024-10-05",
  },
  {
    id: "t6",
    userId: "u5",
    title: "Optimize database queries",
    summary:
      "Analyze and optimize slow database queries for better performance.",
    dueDate: "2024-09-15",
  },
  {
    id: "t15",
    userId: "u5",
    title: "Refactor legacy code",
    summary: "Improve the readability and maintainability of legacy code.",
    dueDate: "2024-10-01",
  },
  {
    id: "t16",
    userId: "u5",
    title: "Conduct code reviews",
    summary: "Perform thorough code reviews for all incoming pull requests.",
    dueDate: "2024-11-10",
  },
  {
    id: "t7",
    userId: "u6",
    title: "Create social media campaign",
    summary: "Develop a social media campaign for the upcoming product launch.",
    dueDate: "2024-10-01",
  },
  {
    id: "t17",
    userId: "u6",
    title: "Monitor campaign metrics",
    summary: "Track and analyze key performance metrics of the campaign.",
    dueDate: "2024-10-15",
  },
  {
    id: "t18",
    userId: "u6",
    title: "Develop content calendar",
    summary: "Plan and draft a content calendar for social media posts.",
    dueDate: "2024-11-05",
  },
]
